services:
  marzban-node:
    # build: .
    image: hub.verycloud.cn/anyproxy/marzban-node:latest
    restart: always
    network_mode: host

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
